name: Style

enable-email-notifications: true

permissions: write-all

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]
    merge_group:

jobs:
    ci:
        name: Check - (${{ matrix.cmds }})
        timeout-minutes: 15
        runs-on: debian
        strategy:
            matrix:
                cmds: ["deno task style:check"]
        steps:
          - name: Install Deno
            run: |
              apt-get update && apt-get install -y curl unzip
              curl -fsSL https://deno.land/install.sh | sh
              # Add Deno to the PATH for subsequent steps
              echo "$HOME/.deno/bin" >> $GITHUB_PATH

          - name: Check out code
            uses: actions/checkout@v6
            with:
                submodules: true

          - name: Install dependencies
            run: deno install --node-modules-dir=auto
            shell: bash

          - name: Run Check
            run: ${{ matrix.cmds }}
            env:
                CI: 1
