name: Style

enable-email-notifications: true

permissions: write-all

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, synchronize]
    merge_group:

jobs:
    ci:
        name: Check - (${{ matrix.cmds }})
        timeout-minutes: 15
        runs-on: deno
        strategy:
            matrix:
                cmds: ["deno task style:check"]
        steps:
          - name: Check out code
            uses: actions/checkout@v7
            with:
                submodules: true

          - name: Install dependencies
            run: deno install --node-modules-dir=auto
            shell: bash

          - name: Run Check
            run: ${{ matrix.cmds }}
            env:
                CI: 1
